= Prisma Cloud Satellite
Alexandre Cezar <acezar@paloaltonetworks.com> 1.0, August 31, 2023:

== About

Prisma Cloud Satellite is an operator designed to manage and orchestrate the deployment of Prisma Cloud functions that are required for Prisma Cloud to perform different tasks in K8s clusters, such as  Configuration Visibility, Application Detection, Asset tracing, Container Exposure and Security Posture.

Customers can easily install the Satellite using their traditional deployment mechanisms and start getting visibility over their K8s clusters.

[IMPORTANT]
Satellite does not have any enforcement security capabilities, and it's not an alternative for Prisma Cloud Defender as both tools serve different purposes.

=== Additional Information

==== https://github.com/alexandre-cezar/satellite-docs/blob/main/Concepts.adoc[Concepts]
==== https://github.com/alexandre-cezar/satellite-docs/blob/main/Get_Started.adoc[Get Started]
==== https://github.com/alexandre-cezar/satellite-docs/blob/main/System_Requirements.adoc[System Requirements]
==== https://github.com/alexandre-cezar/satellite-docs/blob/main/Automating__Satellite_Deployment.adoc[Automating Satellite Deployments]
