= System Requirements
Alexandre Cezar <acezar@paloaltonetworks.com>, August 31, 2022:

Your system must meet specific requirements for the Satellite to be successfully installed.

*Connectivity*: +
Satellite need outgoing access to the following Prisma Cloud domains and subdomains. +

- prismacloud.io
- amazonaws.com
- gcr.io

If you have firewalls blocking this traffic, add the following values to their allow lists:

- *.prismacloud.io
- gcr.io
- *.amazonaws.com

*Host Requirements* +
As a minimum, Satellite requires a K8s Node that can dedicate 256MB RAM and 900mCPU.

*Supported K8s Platforms and versions* +
Satellite is supported on the following platforms and versions:

|===
s|Platform s|Version
|AWS EKS
|1.24, 1.25, 1.26, 1.27

|Azure AKS
|1.24, 1.25, 1.26, 1.27

|Google GKE
|1.24, 1.25, 1.26, 1.27
|===

## Service Account Permissions

### Satellite Manager's roles/permissions

#### Cluster role
```
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
```

#### Role
Satellite only has these permission with it's own namespace
```
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: [ "get", "list", "create", "update", "patch"]
```
### Scanner/Job roles

#### Cluster role

```
- apiGroups: [""]
  resources: ["pods","pods/log","services","endpoints","nodes","namespaces"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses","networkpolicies"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets","replicasets","daemonsets"]
  verbs: ["list", "get", "watch"]
```
